### PR TITLE
Add architecture document

### PR DESCRIPTION
**Pull request by IanVS**
One of the Storybook maintainers asked for some details of how the Vite builder works, so I thought I'd take the chance to write up a bit of a document that might help other contributors start to understand how the code works.  

It's still a WIP, but I'm opening the PR now so that @jonniebigodes can refer to it, and will have updated changes as I push them up.

### CODE REVIEW

**Review by joshwooding — APPROVED** [review]

**Comment by dohooo** [comment]
Awesome!

**Comment by jonniebigodes** [comment]
@IanVS and @joshwooding I'm taking a pass at the docs and polishing them a bit if both of you are ok with it so that it not only helps me but also new contributors. I'll let you know once the changes are up so that we can continue to work on this. Sounds good?

Hope both of you have a great weekend!

**Comment by joshwooding** [comment]
@jonniebigodes Sounds good :)

**Comment by IanVS** [comment]
@jonniebigodes what is the current status on this?

**Comment by jonniebigodes** [comment]
@IanVS, this is not forgotten. I just hadn't had the time to follow up on it. Next week when I come back, I plan on going through it and updating it. I'll ping you, and we can discuss it a bit more. Sounds good?

**Comment by IanVS** [comment]
I'll just close this out, it's sat for too long, and it seems to be blocked on a review.

**Pull request closed without merging**
