### PR TITLE
Migrate to pnpm workspace

### PR DESCRIPTION
**Pull request by fdc-viktor-luft**

### CODE REVIEW

**Comment by zheeeng** [comment]
after `pnpm storybook --filter example-react` reports `ERR! Error: [vite-plugin-mdx] "react" must be installed`

**Comment by fdc-viktor-luft** [comment]
@zheeeng Yes :+1:

That is exactly the problem with demo PR: See here: https://github.com/eirslett/storybook-builder-vite/issues/55#issuecomment-914203496 for the related post 🙂

**Comment by chasm** [comment]
Any progress here?

**Comment by natebowang** [comment]
I was hit by this issue as well.

**Comment by fdc-viktor-luft** [comment]
I'll try to find some time rebasing my PR, due to many changes in the meantime. But I assume, the problem still exists.

**Comment by joshwooding** [comment]
Thanks for the work @fdc-viktor-luft. Sadly I don't think we'll continue this, sorry.

**Pull request closed without merging**
