### PR TITLE
Update dependencies in examples

### PR DESCRIPTION
**Pull request by IanVS**
This bumps us to storybook 6.5.0-beta.0 and vite 2.9.6.

### CODE REVIEW

**Comment by IanVS** [comment]
Interesting, the upgrade to @storybook/test-runner broke at https://github.com/storybookjs/test-runner/releases/tag/v0.0.5-next.1.  Taking a look at why that broke...

**Comment by IanVS** [comment]
I updated the test runner to the canary from https://github.com/storybookjs/test-runner/pull/101, and it is passing locally now, without dumping a bunch of old storybook packages in `examples/react/node_modules` anymore.

**Comment by IanVS** [comment]
Oh interesting, it seems that any tests running with `--stories-json` are failing in the windows runner.  I wonder why...

**Comment by IanVS** [comment]
This definitely surfaced a few issues with the test-runner, so that was fun.  :-D

I think this is ready to review now, though.

**Review by shilman — APPROVED** [review]
Working great for me. Thanks @IanVS ! 🙏

**Pull request merged**
